:PROPERTIES:
:ID:       31443d4f-7623-467c-b026-ef20db7d08eb
:END:
#+title: FA3-Flags 4 & 5
        #+created: [2025-03-07 Fri 13:13]
        #+last_modified: [2025-03-07 Fri 13:13]
* Lateral Movement
Having cracked the passwords for jason and mysql reaccessing the server via ssh as the mysql server will place us in the mysql home /var/lib/mysql. Looking at the contents of the directory we find a .file.passwd.swap file, this is an autosave file from vim. We can recover the file contents through vim -r file.passwd, this gives us a starting point for the next part of the attack. The contents has what is likely to be the username for the mysql database/shell, to access we will utilise the command mysql which is also in this folder.
* Frontend where?
The question then is what are we using this access for, we're free to move around the sql databases now, but let's have a snoop to see if we can find a front end to the database. Checking /var/www shows that we have a website with an admin folder, inside the admin folder is index.php, opening this in your web browser of choice has a username:password prompt. Inputting data into both fields of this prompt tells us that the users are stored within the mysql database with their md5 hashed passwords. Let's hash a known string, and input both it and a chosen username into the user table in the database.
* mySQL
A few tries at the mysql login we would guess that the username is root and the password is the same as the mysql user. From there we look around

#+BEGIN_SRC mysql
  show databases;
  use gnb;
  select users;
#+END_SRC

We see that the schema for the users table is [id, username, passwordhash] so adding a new user is as simple as ~insert into users values (3, '<username>', '<password hash>');~
* Flag4
Having now inserted valid values into the user table we can move back over to the website and input these new values, the username that we chose and the known string that we hashed. Thus logging in and revealing the 4th flag.
* Flag5
The IP box that we see on login is also interesting, if we press ping it does a ping to the ip address that we input. How about we try doing something else? inputting ~; whoami~ succeeds and tells us we're root, this gives us easy access to the file that we might have seen earlier /root/flag5, run ~; cat /root/flag5~ in our website and reveal flag5.
