:PROPERTIES:
:ID:       7d2f6030-22ad-43c2-a633-a65f8b8838d1
:END:
#+title: Sourdough starter
        #+created: [2024-11-21 Thu 08:45]
        #+last_modified: [2024-11-21 Thu 08:45]
r and water ready for the next bread loaf. Some sourdough starters have been known to be in continual use for hundreds of years!

The activated starter will keep well in the fridge if you feed it every week or you can even freeze it if you are going away or not intending to make bread for a long time.

How To:

Activate the Starter:

Before using this dehydrated sourdough starter, it needs to be activated.  Mix 15g of the starter with 80g of flour and 90g of water in a large jar or similar container. Combine well and leave to stand at room temperature on the bench, covered with a wet tea towel, for 48 hours. Stir occasionally.

It can then be stored in the fridge, or you can begin ‘feeding’ your starter right away – ready to make delicious bread. It is best to ‘feed’ the night before you are going to make bread, or in the morning if baking late in the day.



Feed the Starter:

Bring the starter to room temperature.  Combine equal parts starter, flour and water in a bowl – 50g of each is ideal.   Stir well so that it’s all mixed through and leave in the large jar, covered with a damp towel in a spot that is about 22 – 26o Celsius. If the weather is cool, it may take a little longer.

When the mix has doubled in size and tiny bubbles have formed on the top it is ready to use. You can do a float test by dropping a tiny piece of the starter into a glass of water. If it floats it is ready to use.

To make a loaf of bread, you will need 50g of the ‘fed’ starter mix for 500g of flour. The remaining starter can be stored, fed and continually reused. It will get better and better over time – ready for your next delicious loaf!

It’s best to keep the activated starter in the fridge between feeds unless you are using it daily. Do not completely seal your container as gasses could build up. To maintain your starter, take it out of the fridge about once a week, bring it to room temperature and feed it. If you store your activated starter at room temperature it is best to feed it daily.

Sourdough Bread Recipe

50g ‘fed’ sourdough starter

500g plain flour

350mL water

10g salt

Method:

Combine all ingredients in a bowl until water is absorbed. The dough will be dry and shaggy. Cover the bowl with a damp tea towel and set aside to rest for 1 hour.

Next is the ‘stretch & fold’ step to strengthen the dough by developing the gluten. Gather a portion of the dough, stretch it upwards and then fold it over itself. Rotate the bowl a ¼ turn and repeat the process until you have completed a full circle. Cover again and set aside for 30 minutes. Repeat this process three times in total. With each ‘stretch & fold’ you will notice the dough is holding its shape and will resemble a smooth, round ball.

The dough now needs to rise during the ‘bulk rise’ step. Cover the bowl and place it in a warm spot to rise. This step can take between 3-12 hours depending on the temperature. The dough is ready when it has doubled in size and no longer looks dense.

After the bulk rise, the dough can be shaped. Remove the dough from the bowl and place it on a floured surface. Gently stretch the dough, without overworking to avoid deflating the air. Then starting at the top, fold the dough over towards the centre, give a slight turn and continue to fold over the next section of the dough. Repeat until you have come full circle. Flip the dough over and place it seam-side down. Using your hands, gently cup the sides of the dough to shape it into a smooth, round ball.

For the final proofing stage, place the dough, top side down, onto a clean tea towel that has been sprinkled with rice flour, this will stop the dough from sticking. Place the tea towel and dough into a high-sided bowl that’s about 22cm in diameter at the top. Cover and place in the fridge overnight. The sour flavour of the dough intensifies the longer the dough is left. It can be stored in the fridge for up to three days to intensify the acidic flavour.

Preheat your oven to 240°C. Remove the bowl from the fridge and dust the surface of the dough facing upwards with semolina or plain flour.  This will become the base of the loaf.  Place a piece of baking paper over the bowl and tip it over so that the dough sits on the paper.

The top of the dough can also be sprinkled with flour if you wish to give a rustic feel. Using a sharp knife or blade, score the top of the dough.  You can be as creative as you like here.  The scoring helps steam escape during the cooking process but also creates a nice pattern on your baked loaf.

Place the dough, still with the baking paper underneath, into a Dutch oven or lined baking dish with a lid. Bake for 35-40 mins with the lid on and then remove the lid and bake for a further 10-15 mins or until the surface is golden brown. Remove from the oven and allow to cool completely before slicing to allow the crumb to form. If you cut the bread too soon after baking, the inside with have a gummy texture.

The best way to store sourdough bread is in a paper bag or cotton bag, like The Source calico or large produce bags.  This allows it to breath and it will last a few extra days.  Don’t store in the fridge, but it can be sliced and placed in the freezer.

Storage:

Store the dehydrated sourdough starter in an airtight container in a cool, dry place away from sunlight.

Shelf Life:

Up to 12 months when stored as above. See Best Before date.
