:PROPERTIES:
:ID:       fc6a5151-e376-4728-a3e4-cfd263698245
:END:
#+title: RAAF - 462 SQN
* Mission
462 SQN executes Defensive Cyberspace Operations (DCO), Information Assurance (IA) activities and Counterintelligence (CI) operations IOT secure Air Force Freedom on Manoeuvre (FoM) in cyber space.

In order to achieve their mission 462 SQN provides the following services:

 - ICT Certification/Accreditation (CA)
 - Operational Security Vulnerability Assessment (OPSEC VA)
 - Emanation Security (TEMPEST/EMSEC)
 - Expert Advice (EA)
 - Cyber Incident Response
 - ICT Threat Assessment (TA)
 - ICT Vulnerability Assessment (VA)
 - Education and Training (ET)
* Certification/Accreditation

462SQN is appointed as the Certification Authority for all RAAF ICT systems classified SECRET and below.
** Certification:

The process by which formal assurance has been presented to the Accreditation Authority (AA) displaying that the ICT system is meeting the minimum controls outlined in the Defence Security Policy Framework (DSPF) and Information Security Manual (ISM).
** Accreditation:

Accreditation is the formal approval and acceptance of the residual risk of the ICT system by the AA. The accreditation processes provide Air Force a way of understanding and managing security risks to critical ICT assets.

Air Force units can request CA from 462 SQN through an Air Warfare Centre Task Request Form on the DSN.
* Op Sec Vulnerability Assessment

An Operations Security Vulnerability Assessment (OPSEC VA) conducted by 462 SQN is designed to test the physical, cultural and personnel security posture of your unit with regard to protection of your mission critical ICT systems.

There are 3 levels of complexity that an OPSEC VA can be conducted.
** Level 1 - Desktop Audit: Examines security documentation remotely and determines its compliance with the Defence Security Policy Framework.
** Level 2 - Blue team: 462 SQN OPSEC team deploy to your location in a consultative role, in order to review your unit's physical security posture, documentation and procedures for protecting mission critical ICT systems.
** Level 3 - Red team: 462 SQN members deploy to the location and conduct activities as a simulated adversary or red force. The purpose is to attempt to gain physical access to facilities and systems and assess the availability of Essential Elements of Friendly Information (EEFI) to an outsider.
** Emanation Security

Emanation: All electro-mechanical and electronic signal processing equipment and associated cabling produce emanations in the form of electromagnetic radiation.

These emanations may contain elements of the classified information that an adversary may be able to intercept and analyse and are referred to as Compromising Emanations (CE).

TEMPEST: Code word referring to the investigation and study and control of compromising emanations from information processing equipment.

EMSEC: is designed to deny unauthorised persons information that could be derived from the interception and analysis of unintentional CE from cryptographic equipment and/or classified information processing systems.
*** EMSEC services provided by 462 SQN:

 - Emanation Security Advice
 - Emanation Security Awareness
 - Emanation Security Assessment

Emanation Security Advice: The introduction of new of any configuration change to existing systems can have an EMSEC risk. 462SQN ESS SME’s are available to provide advice on all aspects on EMSEC, including advice on completing an EMSEC threat assessment questionnaire.

Emanation Security Awareness: Providing EMSEC briefs to improve awareness among RAAF staff employed in the operation and maintenance of classified processing systems.

Emanation Security Assessment: Assessments that can be conducted initially and periodically by 462SQN to ensure continued compliance and accreditation. Assessments are usually done often of platforms, facilities and ICT systems when upgraded and those upgrades may impact on the EMSEC profile of the system.
** Expert Advice and Cyber Incident Response
*** Expert Advice

Provides advice regarding Information Assurance and defensive cyber capabilities.

Ranges from certification and accreditation advice, through to personnel security advice and is assessed on a case-by-case basis.
*** Cyber Incident Response

462SQN is able to assist in the identification, isolation, analysis and recovery of computer security incidents. This task may require forensic analysis of digital media, recovery of data and assistance with the re-building or restoration of systems.

Incidents can include cyber-attack, user error, physical system failure or anything else that affects the mission worthiness of CIS.
