:PROPERTIES:
:ID:       701d5737-61d0-4035-993e-58064902fb22
:END:
#+title: Australian Signals Directorate (ASD)

The Australian Signals Directorate (ASD) is a vital member of Australia’s national security community, working across the full spectrum of operations required of contemporary signals intelligence and security agencies: intelligence, cyber security and offensive operations in support of the Australian Government and Australian Defence Forces (ADF).
* Australian Signals Directorate Roles

As Australia’s cryptologic agency, ASD's purpose is to defend Australia from global threats and help advance Australia's national interests.

ASD does this by mastering technology to inform, protect and disrupt.

ASD’s strategic objectives are:

 - Informing - by the covert acquisition of foreign information not publicly available (signals intelligence)

 - Protecting - by comprehensively understanding the cyber threat, providing proactive advice and assistance to improve the management of cyber risk by government, business and the community

 - Disrupting - by applying our offensive cyber capabilities offshore, to support military operations, counterterrorism, counter cyber espionage and serious cyber-enabled crime.
