:PROPERTIES:
:ID:       6fc73595-d9c4-400a-9333-1fb74a0fe13b
:END:
#+title: Navy - Fleet Cyber Unit
* Navy Information Warfare Branch (NIWB)

Navy’s Information Warfare Program. This encompasses the disciplines of Intelligence, Maritime Communications & Information Systems, Information Effects, Electronic Warfare, Tactical Data Networks and Cyber.
** Mission:

The aim of Navy's cyber operations is to fight and win in the information domain by effectively integrating cyberspace effects.

The Navy Information Warfare Framework (NIWF) is the capstone document for Navy’s transformation to meet the challenges of the information age.

The aim of Navy's cyber operations is to fight and win in through the information domain by integrating cyberspace effects.

To realise this aim, Navy’s cyberspace capability development priorities are:

 - Priority 1 - Defend Navy's mission critical systems from adversary collection, manipulation and denial.
 - Priority 2 - Integrate the full spectrum of cyberspace operations within Maritime campaigns and operation.

** Defensive Cyber Operations

DCO involve a range of passive and active cyberspace activities to defend ICT capabilities that enable critical navigation, warfighting, C3, engineering, and administrative functions from multiple complex cyber-attacks.

DCO includes four specific activities undertaken by Navy:

 - Cyber Security operations are actions taken to design, build, configure, secure, operate, maintain, and sustain DIE networks and systems in order to assure data availability, integrity, confidentiality, user authentication, and non-repudiation. Cyber Security operations are a component of Navy’s Cyber worthiness regime.
 - Cyber Vulnerability Assessments are actions taken to dynamically ensure that Navy systems are prepared for and protected against recognised threats and exploits.
 - Cyber Incident Response are actions taken to respond to suspected or confirmed cyber incidents. Navy has a requirement to ensure the ongoing operation of ICT and mission systems in order to deliver on government directed activities. Incident response includes the planning, containment, eradication, recovery and reporting of cyber incidents.
 - Discovery and Counter Infiltration activities are deliberate, authorised defensive actions to defeat imminent or ongoing threats to Navy’s communications capabilities or other designated systems. DCI will be conducted in collaboration with relevant authorities and in accordance with extant policies and instructions.
