:PROPERTIES:
:ID: 96368ecf-43d3-4181-805b-adc93a9ddc9b
:END:
#+title: Information Security Manual
[[file:Information Security Manual (September 2024).pdf][Manual (as at Sep24)]]
* Brief Description
 - Function - is to provide practical guidance on how organisactions can protect their systems and information from cyber threats.
 - Role - is to provide strategic guidance on how organisations can protect their systems and infromation from cyber threats.
 - Purpose - the purpose of the ISM is to outline a cyber security framework that organisations can apply, using their risk management framework, to protect their systems and information from cyber threats.
* ISM Principles and Guidelines
:PROPERTIES:
:ID: 502e2f9c-c4db-4587-9cae-3215026846be
:END:
The purpose of the cyber security principles within the ISM is to provide strategic guidance on how organisations can protect their systems and information from cyber threats.

These Cyber Security Principles are grouped into four key activities:

 - Govern - Identifying and managing risks
 - Protect - Implementing security controls to reduce security risks
 - Detect - Detecting and understanding cyber security events
 - Respond - Responding to and recovering from cyber security incidents

The purpose of the cyber security guidelines within the ISM is to provide practical guidance on how organisations can protect their systems and information from cyber threats.

These Cyber Security Guidelines cover matters in:

 - Governance
 - Physical Security
 - Personnel Security and
 - Information/communications technology security
** ISM Guidelines
It is important to understand how to know how a control is to be implemented.

Security control are broken up into guideline groups. The example below shows Guidelines for Detecting Cyber Security Incidents.

At each guideline, the ISM provide basic definitions of the topic in general as well as some examples organisations can use.

You can see Domain Name System Logs can assist in identifying attempts to resolve malicious domains or IP addresses.
Guidelines for Cyber Security incidents
** ISM Controls
The main reason that you will be referencing the ISM is to look up controls. For Defence, most - if not all - of the controls are to be adhered to whenever possible. Each control refers back to an overarching guideline such as Guidelines for Cyber Security Roles, or Guidelines for Physical Security.

The below excerpt from the ISM shows the Security Controls that apply to providing cyber security awareness training, which falls under Guidelines for Personnel Security, Cyber Security Awareness Training;

Security Controls can be broken down into the following components.

- Control Number: the reference number for the applicable control. On this example the control numbers are 0252 and 1565.

- Revision: the number of times the control has been revised. In this example control 0252 has has been revised six (6) times, whereas control 1565 has not been changed since it has been implemented. It is common and important for controls to be revised when significant changes are made.

- Updated: Updated shows when the control was last updated. In this example both controls were updated in Jun-20.

- Applicability: shows what classification of system this control is applicable to. In this example both controls are applicable for Official, Protected, Secret, and Top Secret systems

While it is not law to comply with ISM, legislation and direction from ADF compels us to utilise the ISM for risk mitigation.
