:PROPERTIES:
:ID:       5bfd8e77-044d-4011-bcba-3db5b7d7282b
:END:
#+title: Policies, Procedures, and Standards
* Policies

Policies, procedures, standards and guidelines should be included in your organisation’s living documents that are periodically evaluated and changed as necessary as part of the Policy Lifecycle.

The Policy lifecycle generally consists of four steps in relation to your security policy and solutions:

 - Plan (adjust) for security in your organisation. Develop the policies, procedures and guidelines that will be implemented and design the security components that will protect your network. Once these documents are designed and developed, you can implement the plans.
 - Implement the plans. Part of the implementation of any policy, procedure or guideline is an instruction period during which those who will be affected by the change or introduction of this new document learn about its content.
 - Monitor the implementation. Ensure that hardware and software, as well as the policies, procedures, and guidelines are effective in securing your system.
 - Evaluate the effectiveness. May include tabletop exercises, vulnerability assessments or penetration testing of the system to ensure the security is adequate.

After the Evaluation step you begin again with the planning step, adjusting security mechanisms that you have in place, continuing on through the cycle.
* Policy, Procedures and Standards

Common policies an organisation should have in place include, but are not limited to:

 - Security Policies
 - Change Management
 - Classification of information
 - Acceptable use
 - Due care and due diligence
 - Due process
 - Need-to-Know
 - Disposal and destruction of data
 - Service level agreements
 - Human resources issues
 - Code of ethics
 - Policies governing incident response
* Security Policy, Procedures and Standards

Security roles start and end with policies. The better policies, the better the security you have enabled on your network. Policies, procedures, standards and guidelines detail what users and administrators should be doing to maintain the security of systems.

Ask yourself, why does an organisation need a security policy?
A security policy:

 - Protects the organisation, the people and the information
 - Establishes what must be done to protect information stored on computers
 - Protects people who are trying to do the right thing

Security Policies are a high level statement, produced by senior management, that outlines both the security capabilities of the organisation and the security goals of the organisation. The main Security Policy can be broken down into additional policies that cover specific topics.
The Defence Security Principles Framework or Protective Security Principles Framework is a good example of this as the policy framework is broken into principles such as governance and controls.

Security policies are not something that you create as a one-time thing. They are evolving documents that are continually evaluated and changed. Continually enhancing, improving and changing these documents based on the way your organisation is changing is referred to as the policy lifecycle.
* Change Management Policies
:PROPERTIES:
:ID:       20951a3f-3d1e-41b7-b471-9e43f66824c3
:END:

The purpose of Change Management is to ensure that proper procedures are followed when modifications are made to the IT infrastructure.

Change management is a risk mitigation approach and refers to the structured approach that is followed to secure a company’s assets. Changes should be subject to management approval.

Changes can be prompted by a number of events, including:

 - New Legislation
 - Updated versions of software/hardware
 - Implementation of new software/hardware
 - Improvements to infrastructure

The change management process should include:

 - Various stages
 - Method to request a change
 - Review and approval process for the requests
 - Examination of consequences of the change
 - Resolution (mitigation) of any detrimental effects the change might incur
 - Implementation of the change
 - Documentation of the process as it related to the change
* Data Policies
:PROPERTIES:
:ID:       d0e51239-f364-4cf2-a488-06adc3158a7c
:END:
Data policies are important due to the integration of third parties and sharing of data. Data can be shared for the purpose of processing or storage.

Control over data is a significant issue in third party relationships, so this also needs to be addressed. For example, who owns the data if it is shared with another organisation and/or joint developed together?

Data policies assist these issues and can be broken down in the following areas.

 - Data Ownership
 - Unauthorised Data Sharing
 - Data Backups
 - Classification of Information
 - Data Labelling, Handling, and Disposal
 - Need-to-Know
 - Disposal and Destruction Policy
** Data Ownership

In simple terms, data requires a data owner and data ownership is a business function. The following points are considered when creating or amending data ownership policies.

 - When dealing with third parties you need to consider who owns the data and who will be backing up the data
 - All data elements needs to be defined in the business
 - The requirements for security, privacy and retentions need to be established for data being stored
 - Not all data requires the same handling restrictions, but all data requires these characteristics defined. This is the responsibility of the data owner
** Unauthorised Data Sharing
 - Can be a significant issue, data has value and it is frequently used for secondary purposes
 - Ensuring that all parties in the relationship understand that the data-sharing requirements are an important prerequisite
 - Ensure that all parties understand the security requirements involving shared data
** Data Backup
When it comes to data backup, the following should be implemented:
 - Data ownership requirements, including backup responsibilities
 - Data backup requirements include determining the level of backup, objective of restoration as well as the level of protection
 - Data backups should executed by operational IT personnel. This helps to determine the backup responsibilities and developing operational procedures that ensures having adequate backups, are important security elements

For third parties:

 - Data backups are generally only considered when things go wrong. Generally they are not taken into account from a security perspective in regards to third party contractors

 - Does the organisation have a backup strategy? Do they store the information at an offsite storage facility? This is managed by a third party and should be clear and concise to ensure your data is retained.
** Classification of Information
A key component of IT security is the protection of information processed and stored on computer systems/networks. Organisations deal with many different types of information, they need to recognise that not all information is of equal importance or sensitivity.

Information requires classification of information into various categories with its own requirements for handling

 - Factors that affect classification can include:
   - The value to the Organisation
   - The age of the information
   - Laws or Regulations

Knowing the categories and how to handle data according to its category is essential for protecting the confidentiality of the data
 - TOP SECRET
 - SECRET
 - PROTECTED
 - OFFICIAL
 - UNOFFICIAL

Some common business classifications are:
 - Publicly Releasable
 - Proprietary
 - Company Confidential
 - For Internal Use Only
** Data Labelling, Handling and Disposal

System users can utilise data classification programs include data labelling, which enables personnel working with the data to know whether it is sensitive and to understand the levels of protection required.

When data leaves this protection (printed, downloaded/copied) it is necessary to ensure continued protection by other means. You will look at this in more detail in coming modules.

 - Data labelling assist users in fulfilling their responsibilities
 - Training is essential in ensuring proper data handling and disposal and;
 - If personnel are intimately involved in tasks associated with data handling and data destruction/disposal can act as a security control
*** Need to Know
 - Need to know goes hand in hand with Least Privilege
 - Each individual in the organisation is supplied with only the absolute minimum amount of information and privileges they need to perform their work tasks
 - To obtain access to any piece of information an individual must have a justified need to know
 - Policy should address who in the organisation can grant access to information and who can assign privileges to employees
*** Disposal and Destruction Policy

"Dumpster Diving" has been a technique used for decades to gather sensitive information. The crumpled sensitive document, the printer ribbon that can has embedded information, all this can be gathered because the organisation does not have a robust destruction policy in place.

An Organisation must be concerned about not only paper trash but Information stored on discarded objects i.e. computers, HDDs. It is critical for every organisation to have strong disposal and destruction policies and related procedures.

As a baseline, good destruction techniques are:
 - Anything that may be useful (important documents) to an intruder should be shredded
 - Magnetic storage should have all data deleted and overwritten with ones and zeroes and random characters at least three times
 - Another method of destruction can include degaussing – strong magnetic field to effectively destroy media
 - Shredding of CD’s & Floppy disks
* Password and Account Policies
:PROPERTIES:
:ID:       4cea317a-4575-4ebd-9189-a40595b87746
:END:

 - Username/password combination is the most common means of controlling access to applications, web sites, computer systems

 - An average user will have a dozen or more username and password combinations – home, work, school

 - To select a good, difficult to guess password, organisations implement and enforce password policies which typically have the following components:
** Password Complexity
[[id:a15a7106-30cd-4364-a022-af240a633cba][Password entropy equation]]
Password complexity specifies that the password must meet the minimum length requirement and have characters from at least three of the following four groups:

 - English Uppercase Characters (A through Z)
 - English Lowercase Characters (a through z)
 - Numerals (0 through 9)
 - Non-alphabetical characters e.g. !@#$%
** Account and Password Expiration

 - A common restriction that can be enforced in many access controls mechanisms is either (or both) an account expiration or password expiration feature

 - Passwords must expire as they are more likely to be broken if they remain unchanged

 - Microsoft recommends setting this value to 42 days if you want to enforce strong password usage

 - To keep users from changing their password to the same value as the old one/one they used last time around, you should enable password history – should be set to 24 so 24 unique passwords must be used by any given user before they can be reused again

 - You should also configure a minimum number of days that can exist between password changes
** Password Recovery

 - Users will occasionally forget their passwords

 - Often occurs after the user has changed it/after a long weekend/holiday

 - Most Operating Systems allow the administrator to change the value for the user who has forgotten theirs

 - New value allows the user to log in and then immediately change it to another value that they can remember
** Account Disablement

 - When a user will be gone from a company for an extended period of time (E.g. maternity leave) their account should be disabled until they return

 - When user leaves an organisation (E.g. termination) their account should be disabled immediately
** Account Lockout
When a user is attempting to log in but given incorrect values; locking this account is necessary to prevent a would-be attacker from repeatedly guessing at password values until they find a match (Brute Force).

Can configure lockout policies at the local level on the workstation (Local Security Policy) or at the domain level (Group Policies), values that can be configured are as follows:

 - Account Lockout Duration – When the system locks the account, this is the duration before it is unlocked. Windows – 0 – 99,999 minutes

 - Account Lockout Threshold – Setting determines how many incorrect attempts a user can give before the account is locked. Windows – 0 – 999 failed attempts

 - Reset Account Lockout Counter After – Value specifies the number of minutes to wait between counting failed login attempts that are part of the same batch of attempts
** Password History
Password history is a reference to previously used passwords by an account.

Security Policy should prohibit the reusing of passwords at least for a set number of previous passwords:

The following three rules work together :

 - Enforce Password History - tells the system how many passwords to remember and does not allow a user to reuse an old password

 - Maximum Password Age - specifies the maximum number of days a password may be used before is must be changes

 - Minimum Password Age - specifies the minimum number of days a password must to used before it can be changed again
** Password Re-use
Reuse restrictions are policy to determine:

 - Whether passwords can/cannot be reused

 - Frequency of reuse
** Minimum Password Length

 - Is critical to password-based security

 - The true strength of the password lies on its entropy or randomness

 - The longer the entropy or randomness, the greater the key space that must be searched for random matching

 - Increasing the password length and complexity is the easiest way to increase entropy in a password

** Protection of Passwords
Protections for passwords should be stressed in policy.

Some password protection considerations are:

 - Not writing down passwords – where others can find them

 - Not saving passwords

 - Not allowing automated logins

 - Not sharing passwords with others
