:PROPERTIES:
:ID:       6ce880c2-3a77-48c9-99d3-19f02ca67c58
:END:
#+title: Research Cyber Publications
* ADF Cyber Doctrine
ADF Cyber has several different publications, directives and frameworks that govern the need and requirements of the cyber workforce.

These include but are not limited to:

 - ADF‑I‑3 Cyberspace Operations Edition 1 AL1, dated 27 September 2021
 - Defence Cyber Security Strategy
 - CA Directive 02-20 – Army Cyber Security and Worthiness Operations Governance Framework dated 30 March 2020
 - Defence – Cyberspace Security Governance Framework dated 25 January 2016
 - CJC Directive 07/20 – ADF Cyberworthiness Governance Framework dated 17 December 2020
 - ANP4604 - Navy Cyberspace Operations (Yet to be released)
 - ANP4605 - Navy Cyberworthiness (Yet to be released)

We will only focus on the ADF-I-3 Cyberspace Operations for this lesson
** ADF-I-3 Cyberspace Operations
 - ADF-I-3 Cyberspace Operations
 - Released July 2020
 - The aim of the ADF-I-3 Cyberspace Operations is to provide strategic and operational guidance on the operational use of cyberspace in the joint environment.
* Types of Publications
** [[https://www.recordedfuture.com/resources/][Recorded Future]]
:PROPERTIES:
:ID:       3eac8898-b786-40df-a145-a39d3966aac8
:END:
Recorded Future combines analytics with human expertise to produce superior security intelligence that disrupts adversaries.

Using a "Temporal Analytics Engine," Recorded Future provides forecasting and analysis tools to help analysts predict future events by scanning sources on the internet and extracting, measuring, and visualizing the information to show networks and patterns in the past, present, and future.

Their aim is to organize and analyze threat data in an entirely new and different way for better, faster security.

This website provides valuable and current information via podcasts, webinars, blogs and daily threat reports.
** [[https://www.fireeye.com/mandiant.html][Fire Eye]]
:PROPERTIES:
:ID:       151528a0-99b0-4ec5-91ae-7ffd11a0de6b
:END:
It provides hardware, software, and services to investigate cybersecurity attacks, protect against malicious software, and analyse IT security risks.
** [[https://www.nist.gov/cyberframework][NIST Framework]]
:PROPERTIES:
:ID:       9623809b-1bc5-4dc7-9247-85f45362c9b3
:END:
 - The Framework is voluntary guidance based on existing standards, guidelines, and practices for organisations to better manage and reduce cybersecurity risk.
 - Aids to foster risk and cybersecurity management communications amongst both internal and external organisational stakeholders.
** [[https://www.crowdstrike.com.au/][Crowdstrike]]
:PROPERTIES:
:ID:       6eb8b75f-7b95-4e8f-a78e-1a2ebdb3c935
:END:
CrowdStrike is a leading cybersecurity company protecting customers from all cyber threats by leveraging its Security Cloud to stop breaches.
** [[https://otx.alienvault.com/][AlienVault]]
:PROPERTIES:
:ID:       0fe213db-92ad-403e-9415-1353fa108028
:END:
AlienVault® OSSIM™, Open Source Security Information and Event Management (SIEM), provides you with a feature-rich open source SIEM complete with event collection, normalization and correlation. Launched by security engineers because of the lack of available open source products, AlienVault OSSIM was created specifically to address the reality many security professionals face: A SIEM, whether it is open source or commercial, is virtually useless without the basic security controls necessary for security visibility.

 - Gain FREE access to over 19 million threat indicators contributed daily
 - Collaborate with over 100,000 global participants to investigate emerging threats in the wild
 - Quickly identify if your endpoints have been compromised in major cyber attacks using OTX Endpoint Security™.
 - Share your threat research and subscribe to pulses from other OTX contributors to stay up to date with their threat research.
 - Leverage the latest OTX threat intelligence directly in your AlienVault USM™ or AlienVault OSSIM™ environment
 - Synchronise OTX threat intelligence with your other security products using the OTX DirectConnect API
** [[https://talosintelligence.com/][Talos Intelligence]]
:PROPERTIES:
:ID:       d37591fc-2912-444a-a19a-eccb17a29c99
:END:

 - Cisco Talos Intelligence Group is one of the world's largest commercial threat intelligence teams, comprised of world-class researchers, analysts and engineers.
 - Talos defends known and emerging threats discovers new vulnerabilities in common software, and interdicts threats in the wild before they can further harm the internet.
 - Talos maintains the official rule sets of Snort.org, ClamAV, and SpamCop, releasing many open-source research and analysis tools.
** [[https://www.virustotal.com][Virus Total]]
:PROPERTIES:
:ID:       975f329d-dbbc-40c5-bd47-c5b2021eb58c
:END:
Analyse suspicious files and URLs to detect types of malware and automatically share them with the security community.

VirusTotal inspects items with over 70 antivirus scanners, URL/domain blacklisting services, and a myriad of tools to extract signals from the studied content. Users can select a file from their computer using their browser and send it to VirusTotal. VirusTotal offers several file submission methods, including the primary public web interface, desktop uploaders, browser extensions and a programmatic API. The web interface has the highest scanning priority among the publicly available submission methods. Submissions may be scripted in any programming language using the HTTP-based public API.
** [[https://securityonionsolutions.com/][Security Onion]]
:PROPERTIES:
:ID:       255e945b-2650-4dc2-a6d5-06dc8db859cb
:END:
A free and open-source platform for threat hunting, network security monitoring, and log management. Security Onion includes best-of-breed open-source tools such as Suricata, Zeek, Wazuh, and Elastic Stack, among many others.

Products include the Security Onion software and specialized hardware appliances built and tested to run Security Onion.

The Security Onion user base is large, and often others have run into similar problems or have asked questions that might help you with your own Security Onion installation or troubleshooting.

Browse the Security Onion official discussion forums to find support on common issues. Ask for help from other community members, or return the favour by offering your solutions to other users' discussions.
** [[https://github.com/][GitHub]]
:PROPERTIES:
:ID:       a8216b43-038f-4892-8a43-c54adbef9913
:END:
Built for developers, you can host and review code, manage projects, and build software. Millions of developers and companies create, ship, and maintain their software on GitHub—the world's largest and most advanced development platform.

APT notes –a repository of publicly-available papers and blogs (sorted by year) related to malicious campaigns/activity/software associated with vendor-defined APT (Advanced Persistent Threat) groups and/or tool sets.
** [[** http://www.malwaredomainlist.com/][Malware Domain List]]
:PROPERTIES:
:ID:       06b2a753-7a55-4b0b-911b-984599f0c710
:END:
Malware Domain List was designed as a community project to catalogue compromised or dangerous domains. Included alongside the list of domain URLs and IPs is a description of the type of threat – for instance, a Ransomware or Trojan download – as well as the registrant, reverse look-up and ASN. The website is updated roughly once every two weeks.
** [[https://isc.sans.edu/][SANS - Internet Storm Centre]]
:PROPERTIES:
:ID:       4f06feff-b362-4045-8429-31f08ef0e8dc
:END:
Internet Storm Centre Suspicious Domains – weighted lists based on tracking and malware lists from different sources. Domains are categorised depending on the sensitivity level– either low, medium, or high sensitivity.

The Internet Storm Center (ISC) is a website overseen by the SANS Institute that monitors current online security attacks and publishes information about them. The site is often referred to as an Internet warning system, functioning as a kind of cybersecurity counterpart to the early warning systems established to mitigate the risk of harm from various natural disasters and other dangerous events.

The Internet Storm Center is manned by volunteer security experts known as “handlers,” who usually work one 24-hour shift a month and report in a blog post known as a “diary.” The site gets a great deal of input from an active readership of tens of thousands of people who report attacks and anomalous behaviours on their networks. The vigilance of handlers and members means that the Internet Storm Center can often break the news of an attack or a new type of threat before commercial security vendors can.
** [[http://www.malware-traffic-analysis.net/index.html][Malware Traffic Analysis]]
:PROPERTIES:
:ID:       5c20dfee-4b47-474a-926a-9a24cd6a3e8f
:END:
Brad at Malware Traffic Analysis manages a blog on malware and exploit kit traffic. He updates his blog daily with very timely analysis of new malware infections and shares recent projects on malware samples on his Twitter feed.

The toolkit includes [[id:d9921abd-a2c9-4e7d-9dea-7aada8772c30][Wireshark]] and [[id:255e945b-2650-4dc2-a6d5-06dc8db859cb][Security Onion]].
** [[https://www.threatminer.org/index.php][ThreatMiner]]
Hunters can visit the ThreatMiner website to perform data mining for IOCs. The website’s primary function is to free analysts from data collection and provide intelligence analysts with a portal to carry out their tasks, from reading reports to pivoting and data enrichment – all from a single portal.

ThreatMiner is a threat intelligence portal that enables analysts to research under a single interface. It is used in the SANS FOR578 Cyber Threat Intelligence course. API integration is available for many industry-leading platforms, including:
https://www.misp-project.org/modules/
[[id:e2132abc-42a1-49d8-a0fa-96b3dfaa3100][Splunk]]
https://www.demisto.com/integrations/
https://insightconnect.help.rapid7.com/page/plugins
https://exchange.xforce.ibmcloud.com/hub/extension/f3eb7fd27dc1bf509affd101375695b8
* Review Questions
Q1 - What is the aim of ADF-I-3 - Cyberspace Operations?

A1 - Provide strategic and operational guidance on the operational use of cyberspace in the joint environment.

Q2 - Name 3 types of cyber publications?

A2 - Blogs, webinars and websites.

Q3 - What is one of the risks of using cyber publications?

A3 - May let the malicious actor know that their actions have been discovered. Lots of information availiable, can waste time searching.

Q4 - Name three websites currently being used for research by ADF.

A4 - Recorded Futures, NIST Framework, Mandiant Fireeye, ACSC, Crowdstrike, Talos Intelligence, Virus Total, Alien Vault.
