:PROPERTIES:
:ID:       886acc72-cf28-4af0-a0e8-4b02575186d1
:END:
#+title: Risk Awareness and the Importance of Policies
* Cyberspace Risk
Risks in cyberspace are varied, numerous and continually evolving. Even the best cybersecurity practices may not protect against a determined insider or an unknown vulnerability. These risks can be countered, or at least mitigated, with:

 - sound cybersecurity foundations, including cyberspace hygiene
 - a mature cyberworthiness assessment regime
 - a skilled cyberspace workforce supported by good policy
 - robust technical solutions.

RISK = Threat (capability, intent and opportunity) + Vulnerability (technical, procedural and cultural)
* Risk Awareness
Risk awareness needs to be recognissed when working with third parties. When two or more systems have been connected and the technical aspects are completed, consideration should be made to the security of the connection.

This can include:
 - Indentifying the risk
 - Assessing the risk and;
 - Taking the appropriate steps to reducing the risk to an acceptable level.
* Risk Awareness with Third Parties
Security and privacy concerns should be written into interoperability agreements, which are explained further into this module.

Some factors to consider regarding Security Policies are:
 - Balancing available resources
 - The business requirements of the relationship

This requires an understanding of the risks and how these risks are handled throughout the relationship with other parties.

This involves both organisations:
 - Communicating with each other to share information regarding risk.
 - Putting mechanisms in place to facilitate sharing between the organisations.
 - The level and frequency of information sharing is contingent on the security needs of the organisations involved and how extensive the partnership between the organisations is.
