:PROPERTIES:
:ID:       a6fe5574-a786-4638-8ed9-795ba028fa50
:END:
#+title: ANU Breach
* Summary
 - Threat actor gained access in Nov 2018 through a sophisticated no-click spearfishing email
 - Threat actor dwell time in this initial access was six weeks
 - Threat actor gained access to Enterprise Systems Domain (ESD) containing the following systems and data
   - Human resources
   - Financial management
   - Student Admin
   - Enterprise e-forms
 - Actor able to copy and steal an unkown quantity of data contained in the above systems.
 - There is evidence that may suggest the same actor unsuccessfully attempted to regain access in February 2019
 - Indicators of Intrusion first discovered in April 2019
 - Breach was confirmed on 17 May 2019 and subsequently reported to Vice-Chancellor the same day
 - Northrop Grumman engaged to assist with the security breach
* Actionable Intelligence
* Dwell Time
 - Dwell time refers to the amount of time the actor spent on the network undetected, This is significant insofar as it dictates the ability for an attacker to
* Targets
 - Personal identifiable information
* CIA impacts
Confidentiality and Integrity of the Data were affected in this attack. The
** Confidentiality
** Integrity
* Vulnerabilities
Given the attack vector was non-interactiblethe human vulnerabilities are limited to what gets posted in OSINT sources. Thus most vulnerabilities lie with processes and technologies. One vulnerability is

** People
** Process
** Technology
* Remediation

* Can all the elements of the breach be accounted for

*
